service: bamboo-bites
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: fabiola-aws-dev
  region: eu-north-1

functions:
  hello:
    handler: handler.hello

plugins: 
  - serverless-webpack

package: 
  individually: true